# NumPy Exercises 



#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 fives

In [4]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.random(1)

array([0.08809029])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
b = np.random.standard_normal(25)
b.mean()
b.std()
b

array([ 1.25785281, -0.52179149,  0.67492488,  0.29318327, -0.02003055,
       -0.9998364 ,  0.83638801, -0.57904456, -1.9379792 ,  0.4822212 ,
        0.99705964,  2.0637125 ,  0.19609435, -1.10052265,  0.52846166,
       -0.54267613, -0.54788813,  0.63816664, -0.95247407,  0.86935267,
        0.28518083, -0.44424997,  3.27450694, -1.33882164, -0.712842  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [11]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Create the following 2D matrix. 

[ 1,  2,  3,  4,  5]
[ 6,  7,  8,  9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 25]

In [15]:
array1 = np.arange(1,26).reshape(5,5)

#### Get the sum of all the values in matrix

In [16]:
np.sum(array1)

325

#### Get the standard deviation of the values in matrix

In [17]:
np.std(array1)

7.211102550927978

#### Get the sum of all the columns in matrix

In [18]:
np.sum(array1, axis = 0)

array([55, 60, 65, 70, 75])