# NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
array1 = np.zeros(10)
print(array1)

np.zeros(10)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 fives

In [31]:
array2 = np.ones(10) * 5
print(array2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [11]:
array3 = np.arange(10,51)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [13]:
array4 = np.arange(10,51,2)
print(array4)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
array5 = np.arange(0,9)
array6 = array5.reshape(3,3)
print(array6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [30]:
array_I = np.eye(3)
print(array_I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [25]:
array7 = np.random.random()
print(array7)

0.40760662620860644


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [28]:
array8 = np.random.randn(25)
print(array8)

[ 1.23056296  0.12586304  0.04025099 -0.92722244 -1.20414311  0.57591261
  0.697794   -0.67250082  1.24622562  1.15440342 -0.03936377  0.44491597
  0.16172726  0.70883909  0.05932312  0.36081379  1.36198691  0.0229642
  0.7550132  -0.6364284   1.5196224  -0.83054359 -0.37492299 -0.24361037
 -1.42256381]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [29]:
array9 = np.linspace(0,1,20)
print(array9)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Create the following 2D matrix. 

[ 1,  2,  3,  4,  5]
[ 6,  7,  8,  9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 25]

#### Get the sum of all the values in matrix

#### Get the standard deviation of the values in matrix

#### Get the sum of all the columns in matrix